#!/usr/bin/env atkins
# Atkins CI: https://github.com/titpetric/atkins

name: Atkins CI Go project tests, build

vars:
  build:
    goarch: [arm64, amd64]

env:
  vars:
    GIT_COMMIT: $(git rev-parse HEAD)
    GIT_BRANCH: $(git rev-parse --abbrev-ref HEAD)
    GIT_TAG: $(git describe --tags --always --dirty 2>/dev/null || echo "no-tag")
    GIT_TIME: $(git log -1 --format="format:%aI")
    GIT_STATUS: $(git status --porcelain | wc -l)

jobs:
  default:
    desc: "Run everything needed"
    depends_on: fmt
    steps:
      - task: test:simple
      - task: test:build
      - task: test:run

  release:build:
    vars:
      lastRelease: $(git tag | tail -n 1)
    steps:
      - task: install
      - run: >
          echo "Last release [${{lastRelease != "" ? lastRelease : "None"}}]"

  release:create:
    steps:
      - echo gh release create ${{ semver }} --title ${{semver}} --notes "Release ${{semver}}"
      - for: goarch in ${{build.goarch}}
        run: echo gh release upload ${{ semver }} ./bin/atkins-linux-${{goarch}}

  install:
    desc: "Install atkins"
    depends_on: fmt
    vars:
      goos: linux
    steps:
      - for: goarch in ${{build.goarch}}
        env:
          vars:
            CGO_ENABLED: 0
            GOOS: ${{ goos }}
            GOARCH: ${{ goarch }}
        run: go build -ldflags="-X 'main.Version=${GIT_TAG}' -X 'main.Commit=${GIT_COMMIT}' -X 'main.CommitTime=${GIT_TIME}' -X 'main.Branch=${GIT_BRANCH}' -X 'main.Modified=${GIT_MODIFIED}'" -o bin/atkins-${GOOS}-${GOARCH} .
      - cmds:  # This implements a rename based self-update
          - mv -f /usr/local/bin/atkins /usr/local/bin/atkins.old
          - cp -f ./bin/atkins-linux-$(dpkg --print-architecture) /usr/local/bin/atkins

  fmt:
    desc: "Format the code"
    steps:
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - gofumpt -w .
      - go mod tidy

  test:simple:
    desc: "Simple go test with gotestsum (passthru)"
    passthru: true
    steps:
      - gotestsum ./... -- -count 1

  test:build:
    desc: "Build tests"
    steps:
      - rm bin/*.test -f
      - go test -cover -coverpkg=./... -c -o bin/ ./...

  test:run:
    desc: "Run built tests"
    depends_on: install
    vars:
      testBinaries: $(ls ./bin/*.test | xargs -n1 basename)
    steps:
      - task: docker:up
      - rm -rf coverage
      - for: item in testBinaries
        task: test:detail
        detach: true
      - for: item in testBinaries
        task: test:coverage
      - name: cleanup
        task: docker:down
        deferred: true

  test:detail:
    dest: "Collect per-function test runs"
    requires: [item]
    vars:
      tests: $(./bin/${{ item }} -test.list ^Test.)
    steps:
      - mkdir -p coverage/${{ item }}
      - for: funcName in tests
        summarize: true
        run: ./bin/${{ item }} -test.coverprofile "./coverage/${{ item }}/${{ funcName }}.cov" -test.run "^${{ funcName }}$"

  test:coverage:
    dest: "Collect per-function test coverage"
    requires: [item]
    vars:
      tests: $(./bin/${{ item }} -test.list ^Test.)
    steps:
      - for: funcName in tests
        summarize: true
        run: covertrace --name ${{ funcName }} -i "./coverage/${{ item }}/${{ funcName }}.cov" > "./coverage/${{ item }}/${{ funcName }}.yml"

  docker:up:
    desc: "Bring up docker env"
    steps:
      - docker compose up -d --wait --remove-orphans

  docker:down:
    desc: "Bring down docker env"
    steps:
      - docker compose down
