---
version: "3"

tasks:
  default:
    cmds:
      - task: install
      - task: test

  install:
    cmds:
      - task: fmt
      - go install ./cmd/...

  fmt:
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...

  test:
    cmds:
      - go test -v ./...

  record:
    cmds:
      - task: install
      - rm -f atkins.cast atkins.gif
      - asciinema rec --cols 80 --rows 30 -t "Atkins CI runner example" -c "task run" atkins.cast
      - $HOME/.cargo/bin/agg atkins.cast atkins.gif

  run:
    cmds:
      - task: install
      - atkins -file test/pipelines/atkins.yml

  run:error:
    cmds:
      - task: install
      - atkins -file test/pipelines/atkins-err.yml

  test:detach:
    cmds:
      - task: install
      - atkins -file test-detach.yml
