---
version: "3"

tasks:
  default:
    cmds:
      - task: install
      - atkins

  install:
    cmds:
      - which atkins || go install .
      - atkins install

  release: atkins release
  fmt: atkins fmt
  test: atkins test

  record:
    cmds:
      - task: install
      - rm -rf examples ; mkdir -p examples
      - task: record:fixtures

  record:fixtures:
    cmds:
      - asciinema rec --cols 80 --rows 25 -t "Atkins detach example" -c "atkins -file tests/detach.yml" examples/detach.yml.cast
      - $HOME/.cargo/bin/agg examples/detach.yml.cast examples/detach.yml.gif
      - asciinema rec --cols 80 --rows 25 -t "Atkins depends_on example" -c "atkins -file tests/depends_on.yml" examples/depends_on.yml.cast
      - $HOME/.cargo/bin/agg examples/depends_on.yml.cast examples/depends_on.yml.gif
      - asciinema rec --cols 80 --rows 25 -t "Atkins root_jobs example" -c "atkins -file tests/root_jobs.yml" examples/root_jobs.yml.cast
      - $HOME/.cargo/bin/agg examples/root_jobs.yml.cast examples/root_jobs.yml.gif
      - asciinema rec --cols 80 --rows 25 -t "Atkins nested example" -c "atkins -file tests/nested.yml" examples/nested.yml.cast
      - $HOME/.cargo/bin/agg examples/nested.yml.cast examples/nested.yml.gif

  record:gif:
    cmds:
      - $HOME/.cargo/bin/agg atkins.cast atkins.gif

  test:fixtures:
    cmds:
      - ./tests/detach.yml
      - ./tests/depends_on.yml
      - ./tests/root_jobs.yml
      - ./tests/nested.yml
