---
version: "3"

tasks:
  default:
    cmds:
      - task: install
      - task: test

  install:
    cmds:
      - task: fmt
      - go install ./cmd/...

  fmt:
    silent: true
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...

  test:
    cmds:
      - gotestsum ./... -- -count 1
      - task: test:fixtures

  record:
    cmds:
      - task: install
      - rm -f atkins.cast atkins.gif
      - asciinema rec --cols 80 --rows 30 -t "Atkins CI runner example" -c "task test:fixtures" atkins.cast
      - task: record:gif

  record:gif:
    cmds:
      - $HOME/.cargo/bin/agg atkins.cast atkins.gif

  run:
    cmds:
      - task: install
      - atkins -file test/pipelines/atkins.yml

  run:error:
    cmds:
      - task: install
      - atkins -file test/pipelines/atkins-err.yml

  test:fixtures:
    depends_on: install
    cmds:
      - atkins -file tests/detach.yml -l
      - atkins -file tests/detach.yml
      - atkins -file tests/depends_on.yml -l
      - atkins -file tests/depends_on.yml
      - atkins -file tests/root_jobs.yml -l
      - atkins -file tests/root_jobs.yml
