#!/usr/bin/env atkins
name: Release Atkins binaries

vars:
  semver: $(git tag | tail -n 1)
  image: titpetric/atkins
  build:
    goarch: [arm64, amd64]

jobs:
  default:
    steps:
      - cmd: termshot --filename examples/atkins.png -- atkins
      - for: test in ["detach", "depends_on", "root_jobs", "nested"]
        cmd: termshot --filename examples/${{test}}.png -- atkins -l --file tests/${{test}}.yml
