#!/usr/bin/env atkins
name: Release Atkins binaries

vars:
  semver: $(git tag | tail -n 1)
  image: titpetric/atkins
  build:
    goarch: [arm64, amd64]
  tests: ["detach", "depends_on", "root_jobs", "nested"]

env:
  vars:
    CI: "true"

jobs:
  default:
    tty: true
    steps:
      - termshot --filename examples/atkins.run.png -- atkins --final
      - termshot --filename examples/atkins.list.png -- atkins -l

  test:run:
    tty: true
    steps:
      - for: test in tests
        cmd: termshot --filename examples/${{test}}.run.png -- atkins --file tests/${{test}}.yml --final

  test:list:
    tty: true
    steps:
      - for: test in tests
        cmd: termshot --filename examples/${{test}}.list.png -- atkins -l --file tests/${{test}}.yml
