#!/usr/bin/env atkins
name: Release Atkins binaries

vars:
  semver: $(git tag | tail -n 1)
  image: titpetric/atkins
  build:
    goarch: [arm64, amd64]

env:
  vars:
    CI: "true"

jobs:
  default:
    steps:
      - passthru: true
        cmd: env | grep CI
      - tty: true
        passthru: true
        cmd: termshot --filename examples/atkins.run.png -- atkins --final
      - tty: true
        passthru: true
        cmd: termshot --filename examples/atkins.list.png -- atkins -l --final
      - for: test in ["detach", "depends_on", "root_jobs", "nested"]
        tty: true
        passthru: true
        cmds:
          - termshot --filename examples/${{test}}.run.png -- atkins --file tests/${{test}}.yml --final
          - termshot --filename examples/${{test}}.list.png -- atkins -l --file tests/${{test}}.yml --final
