#!/usr/bin/env atkins
name: Release Atkins binaries

vars:
  semver: $(git tag | tail -n 1)
  image: titpetric/atkins
  build:
    goarch: [arm64, amd64]

jobs:
  default:
    steps:
      - cmd: termshot --filename examples/atkins.run.png atkins
      - cmd: termshot --filename examples/atkins.list.png -- atkins -l
      - for: test in ["detach", "depends_on", "root_jobs", "nested"]
        cmds:
          - termshot --filename examples/${{test}}.run.png -- atkins --file tests/${{test}}.yml
          - termshot --filename examples/${{test}}.list.png -- atkins -l --file tests/${{test}}.yml
